<%-- 
    Document   : managecdkey
    Created on : Oct 1, 2025, 4:21:06 PM
    Author     : Nguyen Quoc Hung - CE190870
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>CD Key Management</title>
        <link href="../css/cdkey.css" rel="stylesheet" type="text/css"/>
    </head>

    <body>

        <h2>CD Key Management</h2>

        <!-- Create form -->
        <form action="${pageContext.request.contextPath}/admin/cdkey" method="post">
            <label>Số lượng Key:</label>
            <input type="number" name="count" min="1" required />
            <button type="submit">Generate</button>
        </form>

        <!-- Tabs -->
        <div class="tabs">
            <div class="tab active" onclick="showTab('unused', event)">Unused Keys</div>
            <div class="tab" onclick="showTab('used', event)">Used Keys</div>
        </div>

        <!-- UNUSED KEYS TAB -->
        <div id="tab-unused" class="tab-content active">
            <h3>Unused CD Keys</h3>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Code</th>
                        <th>Status</th>
                        <th>Generated By</th>
                        <th>Generated Time</th>
                    </tr>
                </thead>
                <tbody>
                    <c:if test="${empty unusedList}">
                        <tr><td colspan="5">No unused keys.</td></tr>
                    </c:if>
                    <c:forEach var="k" items="${unusedList}">
                        <tr>
                            <td>${k.keyID}</td>
                            <td>${k.keyCode}</td>
                            <td>${k.keyStatus}</td>
                            <td>${k.keyGeneratedBy}</td>
                            <td>${k.keyGeneratedTime}</td>
                        </tr>
                    </c:forEach>
                </tbody>
            </table>

            <!-- Pagination -->
            <div class="pagination">
                <!-- Nút Pre -->
                <c:choose>
                    <c:when test="${unusedPage > 1}">
                        <a class="arrow" href="${pageContext.request.contextPath}/admin/cdkey?unusedPage=${unusedPage - 1}&usedPage=${usedPage}">&#9664;</a>
                    </c:when>
                    <c:otherwise>
                        <span class="arrow disabled">&#9664;</span>
                    </c:otherwise>
                </c:choose>

                <!-- Số trang -->
                <c:forEach var="i" begin="1" end="${totalUnusedPages}">
                    <c:choose>
                        <c:when test="${i == unusedPage}">
                            <b>${i}</b>
                        </c:when>
                        <c:otherwise>
                            <a href="${pageContext.request.contextPath}/admin/cdkey?unusedPage=${i}&usedPage=${usedPage}">${i}</a>
                        </c:otherwise>
                    </c:choose>
                </c:forEach>

                <!-- Nút Next -->
                <c:choose>
                    <c:when test="${unusedPage < totalUnusedPages}">
                        <a class="arrow" href="${pageContext.request.contextPath}/admin/cdkey?unusedPage=${unusedPage + 1}&usedPage=${usedPage}">&#9654;</a>
                    </c:when>
                    <c:otherwise>
                        <span class="arrow disabled">&#9654;</span>
                    </c:otherwise>
                </c:choose>
            </div>
        </div>

        <!-- USED KEYS TAB -->
        <div id="tab-used" class="tab-content">
            <h3>Used CD Keys</h3>
            <table>
                <thead>
                    <tr>
                        <th>Key ID</th>
                        <th>Code</th>
                        <th>Used By (username)</th>
                        <th>Used Full Name</th>
                        <th>Used At</th>
                    </tr>
                </thead>
                <tbody>
                    <c:if test="${empty usedList}">
                        <tr><td colspan="5">No used keys.</td></tr>
                    </c:if>
                    <c:forEach var="r" items="${usedList}">
                        <tr>
                            <td>${r.keyID}</td>
                            <td>${r.keyCode}</td>
                            <td>${r.usedBy}</td>
                            <td>${r.usedFullName}</td>
                            <td>${r.usedAt}</td>
                        </tr>
                    </c:forEach>
                </tbody>
            </table>

            <!-- Pagination -->
            <div class="pagination">
                <!-- Nút Pre -->
                <c:choose>
                    <c:when test="${usedPage > 1}">
                        <a class="arrow" href="${pageContext.request.contextPath}/admin/cdkey?usedPage=${usedPage - 1}&unusedPage=${unusedPage}">&#9664;</a>
                    </c:when>
                    <c:otherwise>
                        <span class="arrow disabled">&#9664;</span>
                    </c:otherwise>
                </c:choose>

                <!-- Số trang -->
                <c:forEach var="i" begin="1" end="${totalUsedPages}">
                    <c:choose>
                        <c:when test="${i == usedPage}">
                            <b>${i}</b>
                        </c:when>
                        <c:otherwise>
                            <a href="${pageContext.request.contextPath}/admin/cdkey?usedPage=${i}&unusedPage=${unusedPage}">${i}</a>
                        </c:otherwise>
                    </c:choose>
                </c:forEach>

                <!-- Nút Next -->
                <c:choose>
                    <c:when test="${usedPage < totalUsedPages}">
                        <a class="arrow" href="${pageContext.request.contextPath}/admin/cdkey?usedPage=${usedPage + 1}&unusedPage=${unusedPage}">&#9654;</a>
                    </c:when>
                    <c:otherwise>
                        <span class="arrow disabled">&#9654;</span>
                    </c:otherwise>
                </c:choose>
            </div>
        </div>

        <script>
            function showTab(tabName, event) {
                document.querySelectorAll('.tab-content').forEach(el => el.classList.remove('active'));
                document.querySelectorAll('.tab').forEach(el => el.classList.remove('active'));

                document.getElementById('tab-' + tabName).classList.add('active');
                event.target.classList.add('active');
            }
        </script>

    </body>
</html>
