/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */

package controller;

import java.io.IOException;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.util.List;
import model.CDKey;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Nguyen Quoc Hung - CE190870
 */
@WebServlet("/admin/downloadcdkey")
public class DownloadCDKeyServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        @SuppressWarnings("unchecked")
        List<CDKey> generatedKeys = (List<CDKey>) request.getSession().getAttribute("generatedKeys");

        if (generatedKeys == null || generatedKeys.isEmpty()) {
            response.sendRedirect(request.getContextPath() + "/admin/cdkey");
            return;
        }

        response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        response.setHeader("Content-Disposition", "attachment; filename=GeneratedCDKeys.xlsx");

        Workbook workbook = new XSSFWorkbook();
        Sheet sheet = workbook.createSheet("CDKeys");

        Row header = sheet.createRow(0);
        header.createCell(0).setCellValue("Key Code");
        header.createCell(1).setCellValue("Generated By");
        header.createCell(2).setCellValue("Generated Time");

        int rowNum = 1;
        for (CDKey k : generatedKeys) {
            Row row = sheet.createRow(rowNum++);
            row.createCell(0).setCellValue(k.getKeyCode());
            row.createCell(1).setCellValue(k.getKeyGeneratedBy());
            row.createCell(2).setCellValue(k.getKeyGeneratedTime().toString());
        }

        workbook.write(response.getOutputStream());
        workbook.close();

        // reset attribute
        request.getSession().removeAttribute("generatedKeys");
    }
}
